name: 'OpenID Connect login for NuGet'
description: 'Enable using a GitHub Actions OpenID Connect (OIDC) token in the NuGet credential provider.'
author: 'Joel Verhagen'

branding:
  icon: package
  color: blue

inputs:
  package-source:
    description: 'The package source URL to allow token authentication with.'
    required: true
    default: 'https://api.nuget.org/v3/index.json'
  username:
    description: 'The user account that is configured for GitHub federated tokens.'
    required: true
  install-cred-provider:
    description: 'Install the NuGet token credential provider to default NuGet plugin directory.'
    required: true
    default: true
  cred-provider-url:
    description: 'The URL to fetch the credential provider from. Defaults to the the official distribution.'
    required: false

outputs:
  token-info:
    description: 'The GitHub Actions OIDC token info used by the NuGet credential provider'
  cred-provider-dir:
    description: 'The full path to the credential provider directory, if it exists'

runs:
  using: node20
  main: dist/index.js
